# Generated by Django 3.2.5 on 2022-06-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, choices=[('0', '色情'), ('1', '暴力'), ('2', '引战'), ('3', '违法犯罪')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'v_complaint',
            },
        ),
    ]
