# Generated by Django 3.2.5 on 2022-06-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
