# Generated by Django 3.2.5 on 2022-06-01 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.CharField(blank=True, choices=[('0', '娱乐'), ('1', '生活'), ('2', '科技'), ('3', '运动')], max_length=10, null=True)),
                ('file', models.FileField(max_length=255, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('status', models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=20)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
                ('collected', models.ManyToManyField(blank=True, related_name='collected_videos', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'v_video',
            },
        ),
    ]
