# Generated by Django 3.2.5 on 2022-06-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布'), ('2', '举报中')], max_length=1, null=True),
        ),
    ]
