# Generated by Django 3.2.5 on 2022-06-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20220606_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
