# Generated by Django 3.2.5 on 2022-06-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20220608_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.URLField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(blank=True, max_length=6000, null=True),
        ),
    ]
